# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{clayburn-gen}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rob Ellis"]
  s.date = %q{2010-03-03}
  s.default_executable = %q{clayburn-gen}
  s.description = %q{Clayburn MVC Project genator}
  s.email = %q{kazoomer@gmail.com}
  s.executables = ["clayburn-gen"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".gitmodules",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/clayburn-gen",
     "clayburn-gen.gemspec",
     "lib/clayburn-gen.rb",
     "lib/templates/clayburn-app/127.0.0.1/js/bootstrap.js",
     "lib/templates/clayburn-app/127.0.0.1/js/config.js",
     "lib/templates/clayburn-app/127.0.0.1/js/controllers.js",
     "lib/templates/clayburn-app/127.0.0.1/js/exception.js",
     "lib/templates/clayburn-app/127.0.0.1/js/model.js",
     "lib/templates/clayburn-app/127.0.0.1/web/layouts/application.html",
     "lib/templates/clayburn-app/127.0.0.1/web/public/js/jquery-1.4.1.min.js",
     "lib/templates/clayburn-app/127.0.0.1/web/public/logo.png",
     "lib/templates/clayburn-app/127.0.0.1/web/public/master.css",
     "lib/templates/clayburn-app/127.0.0.1/web/views/exception/general.html",
     "lib/templates/clayburn-app/127.0.0.1/web/views/exception/notfound.html",
     "lib/templates/clayburn-app/127.0.0.1/web/views/home/index.html",
     "lib/templates/clayburn-app/clayburn",
     "lib/templates/clayburn-flat/127.0.0.1/bootstrap.js",
     "lib/templates/clayburn-flat/127.0.0.1/config.js",
     "test/clayburn-gen_test.rb",
     "test/test_helper.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/silentrob/clayburn-gen}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Generator for Clayburn MVC}
  s.test_files = [
    "test/clayburn-gen_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

